<x-guest-layout>
<div class="max-w-4xl mx-auto py-16 px-6">
@include('partials.breadcrumbs', ['breadcrumbs' => [['label' => 'Início', 'url' => route('home')], ['label' => 'Política de Privacidade']]])<h1 class="text-3xl font-black dark:text-white">Política de Privacidade</h1><p class="mt-3 text-zinc-500">Última atualização: 29/09/2026</p><div class="prose dark:prose-invert mt-10">
<h2>1. Responsável pelo tratamento</h2><p>O responsável pelo tratamento é a entidade que explora o Finance Pro AI. Os dados legais devem estar preenchidos antes da disponibilização comercial.</p><ul><li>Denominação: {{ config('legal.company_name') ?: 'A preencher' }}</li><li>NIF/NIPC: {{ config('legal.tax_number') ?: 'A preencher' }}</li><li>Morada: {{ config('legal.address') ?: 'A preencher' }}</li><li>Email: {{ config('legal.email') ?: 'A preencher' }}</li></ul>
<h2>2. Dados e finalidades</h2><p>Podem ser tratados dados de identificação, contacto, autenticação, dados financeiros introduzidos pelo utilizador, dados empresariais e dados técnicos necessários ao funcionamento e segurança.</p><p>As finalidades incluem gestão da conta e workspaces, prestação das funcionalidades, pagamentos, suporte, segurança, prevenção de fraude e cumprimento de obrigações legais.</p>
<h2>3. Fundamento jurídico</h2><p>O tratamento pode basear-se na execução do contrato, obrigação legal, interesse legítimo ou consentimento quando este seja exigido. O consentimento pode ser retirado a qualquer momento.</p>
<h2>4. Prestadores</h2><p>Pagamentos podem ser processados pela Stripe e outras funcionalidades podem depender de prestadores tecnológicos. O Finance Pro AI não pretende armazenar os dados completos do cartão bancário.</p>
<h2>5. Inteligência artificial</h2><p>Algumas funcionalidades utilizam IA para análises e sugestões. As respostas são informativas e não substituem aconselhamento profissional.</p>
<h2>6. Segurança e conservação</h2><p>Aplicamos medidas técnicas e organizativas de segurança. Os dados são conservados pelo período necessário às finalidades aplicáveis e aos prazos legais.</p>
<h2>7. Direitos</h2><p>Podes exercer, nos termos aplicáveis, direitos de acesso, retificação, apagamento, limitação, oposição e portabilidade, e retirar consentimentos. Também podes apresentar reclamação junto da CNPD.</p>
<h2>8. Cookies e tracking</h2><p>Cookies necessários são usados para o funcionamento. Tracking não essencial, incluindo análise, só é ativado após escolha válida. Consulta a <a href="{{ route('legal.cookies') }}">Política de Cookies</a>.</p>
</div></div>
</x-guest-layout>