name: Pint inspect

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress
        env:
          COMPOSER_AUTH: '{"http-basic":{"composer.fluxui.dev":{"username":"${{ secrets.FLUX_USERNAME }}","password":"${{ secrets.FLUX_LICENSE_KEY }}"}}}'
      - name: Run Pint
        run: ./vendor/bin/pint --parallel -v
      - name: Save diff
        run: git diff > /tmp/pint.diff
      - name: Upload diff
        uses: actions/upload-artifact@v4
        with:
          name: pint-diff
          path: /tmp/pint.diff
